name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE: backup_db

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET_MANAGER_URL: op://Production/AzureKeyVaultTest/credentials/url

      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          cargo test --verbose
          AZURE_KEY_VAULT_TEST: ${{ env.SECRET_MANAGER_URL }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.USERNAME }}
          password: ${{ env.TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker tag ${{ env.IMAGE }} ${{ env.USERNAME }}/${{ env.IMAGE }}:latest
          docker push ${{ env.USERNAME }}/${{ env.IMAGE }}:latest
